apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: redis
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: redis
    spec:
      containers:
        - name: redis
          image: redis:alpine
          ports:
             - containerPort: 6379
  selector:
    matchLabels:
       app: redis