apiVersion: apps/v1
kind: Deployment
metadata:
  name: result
  labels:
    app: result
spec:
  replicas: 1
  selector:
    matchLabels:
      app: result
  template:
    metadata:
      name: result
      labels:
        app: result
    spec:
       containers:
          - name: result
            image: dockersamples/examplevotingapp_result:before
            ports:
              - containerPort: 80
                name: result

